package org.alienlabs.hatchetharry.model.channel.consolelog;

public enum ConsoleLogType
{
	ZONE_MOVE, TAP_UNTAP, END_OF_TURN, LIFE_POINTS, TOKEN_CREATION_DESTRUCTION, COUNTER_ADD_REMOVE, REVEAL_TOP_CARD_OF_LIBRARY, DRAW_CARD, GAME, INSERT_DIVISION, SHUFFLE_LIBRARY, COMBAT, REVEAL_HAND, DISCARD_AT_RANDOM, ASK_FOR_MULLIGAN, OK_FOR_MULLIGAN, DONE_MULLIGAN, OK_FOR_MULLIGAN_BUT_ONE_LESS, REFUSE_MULLIGAN
}