package org.alienlabs.hatchetharry.model.channel;

public enum NotifierAction {
	DRAW_CARD_ACTION, END_OF_TURN_ACTION, PLAY_CARD_FROM_HAND_ACTION, PLAY_CARD_FROM_GRAVEYARD_ACTION, PUT_CARD_TO_GRAVGEYARD_FROM_BATTLEFIELD, PUT_CARD_TO_HAND_FROM_BATTLEFIELD, COMBAT_IN_PROGRESS_ACTION;
}
